sudo: required
language: csharp
dotnet: 2.1.302
services:
  - docker
os:  
  - linux
branches:  
 only:
   - master
script:
 - dotnet --info
 - dotnet build src/TomKerkhove.Probes.sln --configuration release
 - dotnet build src/TomKerkhove.Probes.sln --configuration release
 - docker build ./src/ --file ./src/TomKerkhove.Samples.Service/Dockerfile --no-cache