sudo: required
language: csharp
dotnet: 2.1.302
services:
  - docker
os:  
  - linux
branches:  
 only:
   - master
script:
 - dotnet --info
 - dotnet build src/TomKerkhove.Probes.sln --configuration release