version: '1.0'
stages:
- build
- ship
steps:
  BuildingDockerImage:
    stage: build
    title: Building Docker Image
    type: build
    image_name: tomkerkhove/kubernetes-liveness-samples-service
    working_directory: ./src/
    tag: '${{CF_BRANCH_TAG_NORMALIZED}}'
    dockerfile: TomKerkhove.Samples.Service/Dockerfile
  PushingToDockerRegistry:
    stage: ship
    title: Pushing to Docker Registry
    type: push
    candidate: '${{BuildingDockerImage}}'
    tag: 'latest'
    registry: DockerHub
